In [6]:
from geopy.geocoders import Nominatim
geo_local = Nominatim(user_agent='South Korea')

# 위도, 경도 반환하는 함수
def geocoding(address):
    try:
        geo = geo_local.geocode(address)
        x_y = [geo.latitude, geo.longitude]
        return x_y

    except:
        return [0,0]

In [7]:
addr='대구 군위군 삼국유사면'

In [8]:
geocoding(addr)

[36.15227, 128.82066]

In [1]:
import pandas as pd
# 장소 데이터를 불러 옴
restaurant=pd.read_csv(r'data\restaurant.csv')
restaurant

               장소    별점                             주소
0            감성돼지  4.54        대구 수성구 고산로4안길 33-8 감성돼지
1        크루피자 성서점   NaN          대구 달서구 호산동로35북길 76 1층
2              리안  4.48                대구 수성구 교학로4길 48
3            대새목장   NaN          대구 달성군 가창면 가창로93길 523
4            신라식당  4.39               대구 중구 중앙대로 406-8
..            ...   ...                            ...
299   뉴욕뉴욕 바이 켄싱턴   NaN  대구 달서구 두류공원로 200 이월드 83타워 78층
300    뜨삽FMD 수성본점  4.48       대구 수성구 용학로 106-7 뜨삽 수성본점
301  인스퍼레이션디동촌유원지  4.41   대구 동구 효동로6길 57 인스퍼레이션디 동촌유원지
302        바닐라빌리지   NaN         대구 서구 서대구로 152 원진빌딩 1층
303    산중식당 팔공산본점  4.33           대구 동구 팔공산로185길 55 1층

[304 rows x 3 columns]

In [2]:
# 데이터프레임 주소값 추출
address= restaurant['주소']
print(address.head())

0    대구 수성구 고산로4안길 33-8 감성돼지
1      대구 달서구 호산동로35북길 76 1층
2            대구 수성구 교학로4길 48
3      대구 달성군 가창면 가창로93길 523
4           대구 중구 중앙대로 406-8
Name: 주소, dtype: object

In [3]:
# 주소 데이터 깔끔하게 다듬기
add_list=[]
for i in range(len(address)):
    if len(address[i])>=4:
        a = address[i].split(' ')
        add_list.append(" ".join(a[0:4]))
    else:
        a = address[i].split(' ')
        add_list.append(" ".join(a[0:4]))
add_list

['대구 수성구 고산로4안길 33-8',
 '대구 달서구 호산동로35북길 76',
 '대구 수성구 교학로4길 48',
 '대구 달성군 가창면 가창로93길',
 '대구 중구 중앙대로 406-8',
 '대구 중구 동성로1길 46-2',
 '대구 수성구 국채보상로 912',
 '대구 수성구 지범로 43-12',
 '대구 수성구 수성못2길 27-5',
 '대구 동구 동부로 149',
 '대구 수성구 들안로 9',
 '대구 중구 동성로6길 2-23',
 '대구 달서구 달구벌대로 1536',
 '대구 북구 이곡길 35-10',
 '대구 중구 동성로2길 58',
 '대구 중구 동성로1길 46-23',
 '대구 달성군 가창면 헐티로2길',
 '대구 중구 공평로 31',
 '대구 수성구 무학로 78',
 '대구 중구 명륜로 20',
 '대구 수성구 국채보상로186길 81',
 '대구 중구 동성로2길 81',
 '대구 수성구 달구벌대로 2398',
 '대구 수성구 용학로 293-7',
 '대구 서구 달서천로83길 13',
 '대구 중구 동성로2길 21-8',
 '대구 북구 복현로 182-27',
 '대구 달서구 한실로6길 158',
 '대구 서구 국채보상로 308',
 '대구 동구 서촌로 98-1',
 '대구 북구 대현남로2길 60',
 '대구 중구 동성로3길 5',
 '대구 수성구 팔현길 212',
 '대구 달서구 두류공원로 200',
 '대구 동구 동부로34길 10',
 '대구 중구 봉산문화2길 16-3',
 '대구 중구 달구벌대로445길 26-18',
 '대구 달성군 가창면 우록3길',
 '대구 중구 동성로3길 32-20',
 '대구 중구 동성로4길 100',
 '대구 남구 큰골길 35',
 '대구 동구 아양로9길 5',
 '대구 중구 동성로2길 18-6',
 '대구 중구 경상감영길 101',
 '대구 중구 중앙대로 398-1',
 '대구 중구 동성로3길 67',
 '대구 중구 국채보상로125길 14',
 '대구 달성군 가창면 주리2길',
 '대구 남구 현충로15길 13-1',
 '대구 중구 동성로 6-1',
 '대구 서구 와룡로 307',
 '대구 남구 안지랑로 21',
 '대구 중구 동성로6길 45',
 '대구 수성구 수성못2길 3',
 '대구 동구 동부로32길 14',
 '대구 중구 중앙대로77길 22',
 '대구 중구 동성로4길 94',
 '대구 동구 효동로6길 122',
 '대구 동구 팔공산로9길 6-1',
 '대구 수성구 용학로 106-5',
 '대구 달서구 용산로 82',
 '대구 중구 명덕로 173',
 '대구 중구 중앙대로 376-20',
 '대구 남구 대명로 303',
 '대구 중구 달구벌대로 2232',
 '대구 동구 파계로138길 64',
 '대구 중구 국채보상로 696-8',
 '대구 달서구 와룡로 169',
 '대구 수성구 무학로 83',
 '대구 중구 달구벌대로 2085',
 '대구 중구 중앙대로 397',
 '대구 동구 파계로 604',
 '대구 동구 동부로 149',
 '대구 수성구 동원로1길 26',
 '대구 수성구 화랑로 68',
 '대구 동구 팔공로 1334',
 '대구 서구 달구벌대로375길 14-1',
 '대구 동구 파계로 583',
 '대구 중구 국채보상로 571',
 '대구 수성구 들안로 8-5',
 '대구 수성구 무학로 85',
 '대구 동구 동부로 149',
 '대구 수성구 용학로 111',
 '대구 중구 동성로2길 4-15',
 '대구 중구 달구벌대로 2109-32',
 '대구 중구 공평로 79',
 '대구 북구 호암로 51',
 '대구 동구 팔공로206길 4',
 '대구 남구 현충로 256',
 '대구 중구 동성로6길 56',
 '대구 중구 종로 42',
 '대구 달성군 현풍읍 비슬로',
 '대구 수성구 들안로64길 49',
 '대구 동구 파계로 497',
 '대구 중구 동성로2길 18-14',
 '대구 달성군 가창면 우록길',
 '대구 남구 중앙대로51길 38-2',
 '대구 수성구 동대구로20길 66',
 '대구 중구 달구벌대로447길 72-6',
 '대구 남구 현충로 41-3',
 '대구 동구 동부로34길 3',
 '대구 중구 동성로 8-9',
 '대구 중구 동성로3길 32-43',
 '대구 북구 이곡길 35-41',
 '대구 중구 동성로2길 21-5',
 '대구 달서구 야외음악당로 3',
 '대구 중구 동성로6길 61',
 '대구 중구 중앙대로 406-12',
 '대구 달서구 월배로83길 7',
 '대구 달서구 달구벌대로 1254',
 '대구 북구 복현로8길 19-36',
 '대구 동구 동부로 149',
 '대구 달서구 달구벌대로 1545',
 '대구 중구 서성로13길 8',
 '대구 동구 동부로32길 1',
 '대구 동구 동부로30길 34',
 '대구 중구 동성로1길 15',
 '대구 중구 종로 72',
 '대구 중구 동성로2길 5-2',
 '대구 수성구 수성못2길 39',
 '대구 군위군 산성면 산성가음로',
 '대구 달서구 와룡로 169',
 '대구 남구 대명복개로 96',
 '대구 남구 앞산순환로 459',
 '대구 중구 달구벌대로446길 11',
 '대구 동구 효동로2길 47-7',
 '대구 수성구 수성못2길 21',
 '대구 중구 달구벌대로414길 36',
 '대구 달성군 가창면 우록길',
 '대구 남구 현충로 214',
 '대구 동구 팔공산로 1179',
 '대구 달성군 다사읍 다사로',
 '대구 달성군 하빈면 육신사길',
 '대구 중구 동성로2길 49-17',
 '대구 수성구 수성로69길 65',
 '대구 중구 남성로 40-1',
 '대구 달서구 학산로 178',
 '대구 중구 교동3길 26',
 '대구 달서구 한실로6길 158-3',
 '대구 중구 동덕로36길 9-17',
 '대구 중구 명륜로23길 75',
 '대구 남구 대봉로 89',
 '대구 달서구 한실로6길 165-7',
 '대구 중구 동성로6길 61',
 '대구 동구 팔공산로 260',
 '대구 중구 경상감영길 213',
 '대구 중구 동성로2길 50-9',
 '대구 수성구 동원로 6',
 '대구 달서구 와룡로 169',
 '대구 수성구 용학로25길 45',
 '대구 수성구 수성못길 20',
 '대구 달성군 가창면 우록길',
 '대구 동구 동촌로 370',
 '대구 수성구 수성못2길 5',
 '대구 중구 남산로6안길 47',
 '대구 달서구 조암로 40',
 '대구 남구 대봉로 65',
 '대구 수성구 명덕로75길 14-2',
 '대구 중구 중앙대로 406-4',
 '대구 수성구 상록로 39',
 '대구 중구 명덕로 93',
 '대구 수성구 수성못6길 7',
 '대구 중구 달구벌대로445길 26-5',
 '대구 수성구 들안로 87',
 '대구 수성구 고모로 188',
 '대구 달서구 월곡로 268-10',
 '대구 달서구 조암로 105',
 '대구 수성구 들안로77길 11',
 '대구 수성구 무학로17길 21',
 '대구 군위군 부계면 한티로',
 '대구 달성군 가창면 가창로119길',
 '대구 수성구 동대구로 219',
 '대구 중구 달구벌대로 2109-10',
 '대구 중구 봉산문화2길 42-15',
 '대구 중구 공평로8길 46',
 '대구 남구 현충로1길 16',
 '대구 중구 동성로5길 89',
 '대구 동구 파계로116길 49',
 '대구 달서구 조암남로32길 24',
 '대구 달서구 조암로 38',
 '대구 중구 동성로2길 31',
 '대구 남구 장전3길 85',
 '대구 서구 달구벌대로375길 17',
 '대구 동구 동부로 149',
 '대구 중구 공평로 49',
 '대구 중구 남성로 47',
 '대구 남구 큰골5길 5',
 '대구 중구 동성로2길 8',
 '대구 수성구 수성못6길 9',
 '대구 중구 국채보상로151길 10',
 '대구 동구 해동로 107',
 '대구 달서구 진천로9길 30',
 '대구 달서구 야외음악당로39길 54',
 '대구 중구 달구벌대로 2125-11',
 '대구 달성군 가창면 가창로176길',
 '대구 중구 동성로1길 25',
 '대구 북구 칠성시장로7길 9-1',
 '대구 중구 남성로 7-1',
 '대구 동구 동촌로46길 2',
 '대구 중구 큰장로28길 25',
 '대구 수성구 지범로 248-6',
 '대구 동구 동부로32길 20-1',
 '대구 수성구 들안로 125',
 '대구 수성구 국채보상로186길 151',
 '대구 동구 동부로34길 6',
 '대구 중구 동성로2길 4-3',
 '대구 수성구 국채보상로162길 72',
 '대구 중구 동성로3길 32-33',
 '대구 중구 중앙대로66길 20',
 '대구 달성군 가창면 주리2길',
 '대구 중구 동성로3길 32-7',
 '대구 북구 동암로 128-10',
 '대구 중구 중앙대로77길 14',
 '대구 달서구 구마로 97',
 '대구 중구 동성로3길 32-21',
 '대구 중구 공평로 53',
 '대구 중구 중앙대로81길 23',
 '대구 중구 명덕로 333',
 '대구 중구 약령길 33-8',
 '대구 중구 동성로12길 9',
 '대구 중구 동성로1길 67',
 '대구 북구 동북로 218',
 '대구 중구 달구벌대로 2109-37',
 '대구 수성구 무학로 89',
 '대구 중구 동성로4길 13',
 '대구 중구 종로 45-1',
 '대구 동구 동부로 149',
 '대구 수성구 신매로16길 56',
 '대구 중구 동성로4길 20-13',
 '대구 남구 용두길 16',
 '대구 북구 칠곡중앙대로91길 5-11',
 '대구 수성구 청솔로14길 18',
 '대구 수성구 동대구로 95',
 '대구 중구 동성로2길 18-15',
 '대구 중구 동성로2길 12-24',
 '대구 남구 현충로6길 9-2',
 '대구 중구 큰장로26길 6',
 '대구 중구 동덕로14길 47',
 '대구 중구 중앙대로81길 1',
 '대구 달서구 야외음악당로39안길 8',
 '대구 달서구 와룡로 169',
 '대구 중구 봉산문화2길 41',
 '대구 수성구 상록로 39',
 '대구 달서구 두류공원로28길 8',
 '대구 중구 달성로22길 86',
 '대구 수성구 상록로 15',
 '대구 중구 동성로4길 95',
 '대구 중구 공평로 57',
 '대구 달성군 가창면 퇴계길',
 '대구 중구 동성로4길 6',
 '대구 중구 동성로2길 45',
 '대구 중구 동성로4길 43',
 '대구 중구 동성로1길 41',
 '대구 북구 옥산로 96',
 '대구 수성구 수성못2길 55-1',
 '대구 수성구 용학로 76',
 '대구 동구 파계로 497',
 '대구 중구 공평로 26-1',
 '대구 달서구 조암로 58',
 '대구 중구 교동3길 36',
 '대구 동구 화랑로 93',
 '대구 중구 동성로6길 75',
 '대구 수성구 고모로 15-1',
 '대구 동구 효동로2길 33-7',
 '대구 중구 중앙대로79길 24',
 '대구 중구 국채보상로125길 4',
 '대구 북구 동북로 219',
 '대구 수성구 용학로 111',
 '대구 수성구 동대구로77길 33-4',
 '대구 남구 큰골길 46',
 '대구 북구 칠성남로15길 9-1',
 '대구 북구 학정로 284',
 '대구 중구 동성로2길 4-9',
 '대구 중구 달구벌대로 2125-7',
 '대구 중구 동덕로 48-5',
 '대구 동구 신평로 113',
 '대구 동구 동부로 156',
 '대구 수성구 범어천로 48',
 '대구 중구 동성로 8-7',
 '대구 동구 동부로 13-1',
 '대구 수성구 청수로 96',
 '대구 북구 태전로 37',
 '대구 수성구 달구벌대로652길 16',
 '대구 수성구 상록로2길 45',
 '대구 북구 구암로 280-1',
 '대구 수성구 달구벌대로496길 5',
 '대구 달서구 진천로 36',
 '대구 중구 동성로2길 69',
 '대구 중구 공평로8길 14-9',
 '대구 수성구 동대구로80길 73',
 '대구 동구 동대구로 448',
 '대구 북구 침산남로 197',
 '대구 수성구 수성로 393',
 '대구 중구 종로 40',
 '대구 달성군 가창면 녹문길',
 '대구 중구 교동4길 11',
 '대구 중구 달구벌대로 2115-2',
 '대구 중구 관덕정길 13-13',
 '대구 달서구 달구벌대로251길 12',
 '대구 달서구 두류공원로 200',
 '대구 수성구 용학로 106-7',
 '대구 동구 효동로6길 57',
 '대구 서구 서대구로 152',
 '대구 동구 팔공산로185길 55']

In [4]:
restaurant['수정된 주소']=add_list
restaurant

               장소    별점                             주소              수정된 주소
0            감성돼지  4.54        대구 수성구 고산로4안길 33-8 감성돼지  대구 수성구 고산로4안길 33-8
1        크루피자 성서점   NaN          대구 달서구 호산동로35북길 76 1층  대구 달서구 호산동로35북길 76
2              리안  4.48                대구 수성구 교학로4길 48     대구 수성구 교학로4길 48
3            대새목장   NaN          대구 달성군 가창면 가창로93길 523   대구 달성군 가창면 가창로93길
4            신라식당  4.39               대구 중구 중앙대로 406-8    대구 중구 중앙대로 406-8
..            ...   ...                            ...                 ...
299   뉴욕뉴욕 바이 켄싱턴   NaN  대구 달서구 두류공원로 200 이월드 83타워 78층    대구 달서구 두류공원로 200
300    뜨삽FMD 수성본점  4.48       대구 수성구 용학로 106-7 뜨삽 수성본점    대구 수성구 용학로 106-7
301  인스퍼레이션디동촌유원지  4.41   대구 동구 효동로6길 57 인스퍼레이션디 동촌유원지      대구 동구 효동로6길 57
302        바닐라빌리지   NaN         대구 서구 서대구로 152 원진빌딩 1층      대구 서구 서대구로 152
303    산중식당 팔공산본점  4.33           대구 동구 팔공산로185길 55 1층   대구 동구 팔공산로185길 55

[304 rows x 4 columns]

In [9]:
from tqdm import tqdm
latitude = []
longitude =[]

for i in tqdm(add_list):
    latitude.append(geocoding(i)[0])
    longitude.append(geocoding(i)[1])

100%|██████████| 304/304 [05:17<00:00,  1.05s/it]

In [10]:
restaurant['위도']=latitude
restaurant['경도']=longitude

restaurant

,장소,별점,주소,수정된 주소,위도,경도
0,감성돼지,4.54,대구 수성구 고산로4안길 33-8 감성돼지,대구 수성구 고산로4안길 33-8,35.830220,128.704884
1,크루피자 성서점,NaN,대구 달서구 호산동로35북길 76 1층,대구 달서구 호산동로35북길 76,35.850681,128.482226
2,리안,4.48,대구 수성구 교학로4길 48,대구 수성구 교학로4길 48,35.855269,128.650364
3,대새목장,NaN,대구 달성군 가창면 가창로93길 523,대구 달성군 가창면 가창로93길,35.748629,128.620761
4,신라식당,4.39,대구 중구 중앙대로 406-8,대구 중구 중앙대로 406-8,35.857974,128.592298
...,...,...,...,...,...,...
299,뉴욕뉴욕 바이 켄싱턴,NaN,대구 달서구 두류공원로 200 이월드 83타워 78층,대구 달서구 두류공원로 200,35.852239,128.562312
300,뜨삽FMD 수성본점,4.48,대구 수성구 용학로 106-7 뜨삽 수성본점,대구 수성구 용학로 106-7,35.822718,128.639385
301,인스퍼레이션디동촌유원지,4.41,대구 동구 효동로6길 57 인스퍼레이션디 동촌유원지,대구 동구 효동로6길 57,35.879382,128.654675
302,바닐라빌리지,NaN,대구 서구 서대구로 152 원진빌딩 1층,대구 서구 서대구로 152,35.881655,128.555320
303,산중식당 팔공산본점,4.33,대구 동구 팔공산로185길 55 1층,대구 동구 팔공산로185길 55,35.990312,128.694401

In [11]:
restaurant[restaurant['위도']==0]

# place.to_csv('jungu_incheon_coffeeshop.csv')

        장소    별점                        주소              수정된 주소   위도   경도
37     생수정  4.32        대구 달성군 가창면 우록3길 58     대구 달성군 가창면 우록3길  0.0  0.0
47   오퐁드부아  4.38       대구 달성군 가창면 주리2길 104     대구 달성군 가창면 주리2길  0.0  0.0
58    밥을짓다  4.48       대구 동구 팔공산로9길 6-1 1층    대구 동구 팔공산로9길 6-1  0.0  0.0
170  가창닭갈비  4.59  대구 달성군 가창면 가창로119길 13 1층  대구 달성군 가창면 가창로119길  0.0  0.0
209  주리485   NaN  대구 달성군 가창면 주리2길 48 주리485     대구 달성군 가창면 주리2길  0.0  0.0
248   곤지곤지  4.39       대구 달성군 가창면 퇴계길 43-8      대구 달성군 가창면 퇴계길  0.0  0.0
294  까사드테하   NaN   대구 달성군 가창면 녹문길 16-11 1층      대구 달성군 가창면 녹문길  0.0  0.0

In [12]:
# 위도 경도가 0인 주소
address2=restaurant[restaurant['위도']==0]['수정된 주소']
address2

37        대구 달성군 가창면 우록3길
47        대구 달성군 가창면 주리2길
58       대구 동구 팔공산로9길 6-1
170    대구 달성군 가창면 가창로119길
209       대구 달성군 가창면 주리2길
248        대구 달성군 가창면 퇴계길
294        대구 달성군 가창면 녹문길
Name: 수정된 주소, dtype: object

In [13]:
# 주소 데이터 깔끔하게 다듬기
add_list2=[]
for i in address2:
    a =i.split(' ')
    add_list2.append(" ".join(a[:-1]))

add_list2

['대구 달성군 가창면',
 '대구 달성군 가창면',
 '대구 동구 팔공산로9길',
 '대구 달성군 가창면',
 '대구 달성군 가창면',
 '대구 달성군 가창면',
 '대구 달성군 가창면']

In [14]:
from tqdm import tqdm
latitude2 = []
longitude2 =[]

for i in tqdm(add_list2):
    latitude2.append(geocoding(i)[0])
    longitude2.append(geocoding(i)[1])

100%|██████████| 7/7 [00:07<00:00,  1.05s/it]

In [15]:
address2.index

Index([37, 47, 58, 170, 209, 248, 294], dtype='int64')

In [16]:
for i in range(len(address2.index)):
    index_num = address2.index[i]
    restaurant.at[index_num, '수정된 주소'] = add_list2[i]
    restaurant.at[index_num, '위도'] = latitude2[i]
    restaurant.at[index_num, '경도'] = longitude2[i]
restaurant

,장소,별점,주소,수정된 주소,위도,경도
0,감성돼지,4.54,대구 수성구 고산로4안길 33-8 감성돼지,대구 수성구 고산로4안길 33-8,35.830220,128.704884
1,크루피자 성서점,NaN,대구 달서구 호산동로35북길 76 1층,대구 달서구 호산동로35북길 76,35.850681,128.482226
2,리안,4.48,대구 수성구 교학로4길 48,대구 수성구 교학로4길 48,35.855269,128.650364
3,대새목장,NaN,대구 달성군 가창면 가창로93길 523,대구 달성군 가창면 가창로93길,35.748629,128.620761
4,신라식당,4.39,대구 중구 중앙대로 406-8,대구 중구 중앙대로 406-8,35.857974,128.592298
...,...,...,...,...,...,...
299,뉴욕뉴욕 바이 켄싱턴,NaN,대구 달서구 두류공원로 200 이월드 83타워 78층,대구 달서구 두류공원로 200,35.852239,128.562312
300,뜨삽FMD 수성본점,4.48,대구 수성구 용학로 106-7 뜨삽 수성본점,대구 수성구 용학로 106-7,35.822718,128.639385
301,인스퍼레이션디동촌유원지,4.41,대구 동구 효동로6길 57 인스퍼레이션디 동촌유원지,대구 동구 효동로6길 57,35.879382,128.654675
302,바닐라빌리지,NaN,대구 서구 서대구로 152 원진빌딩 1층,대구 서구 서대구로 152,35.881655,128.555320
303,산중식당 팔공산본점,4.33,대구 동구 팔공산로185길 55 1층,대구 동구 팔공산로185길 55,35.990312,128.694401

In [17]:
restaurant[restaurant['위도']==0]

      장소    별점                   주소        수정된 주소   위도   경도
58  밥을짓다  4.48  대구 동구 팔공산로9길 6-1 1층  대구 동구 팔공산로9길  0.0  0.0

In [19]:
restaurant=restaurant.drop(index=restaurant[restaurant['위도']==0].index)

In [20]:
restaurant.reset_index(drop=True,inplace=True)
restaurant

,장소,별점,주소,수정된 주소,위도,경도
0,감성돼지,4.54,대구 수성구 고산로4안길 33-8 감성돼지,대구 수성구 고산로4안길 33-8,35.830220,128.704884
1,크루피자 성서점,NaN,대구 달서구 호산동로35북길 76 1층,대구 달서구 호산동로35북길 76,35.850681,128.482226
2,리안,4.48,대구 수성구 교학로4길 48,대구 수성구 교학로4길 48,35.855269,128.650364
3,대새목장,NaN,대구 달성군 가창면 가창로93길 523,대구 달성군 가창면 가창로93길,35.748629,128.620761
4,신라식당,4.39,대구 중구 중앙대로 406-8,대구 중구 중앙대로 406-8,35.857974,128.592298
...,...,...,...,...,...,...
298,뉴욕뉴욕 바이 켄싱턴,NaN,대구 달서구 두류공원로 200 이월드 83타워 78층,대구 달서구 두류공원로 200,35.852239,128.562312
299,뜨삽FMD 수성본점,4.48,대구 수성구 용학로 106-7 뜨삽 수성본점,대구 수성구 용학로 106-7,35.822718,128.639385
300,인스퍼레이션디동촌유원지,4.41,대구 동구 효동로6길 57 인스퍼레이션디 동촌유원지,대구 동구 효동로6길 57,35.879382,128.654675
301,바닐라빌리지,NaN,대구 서구 서대구로 152 원진빌딩 1층,대구 서구 서대구로 152,35.881655,128.555320
302,산중식당 팔공산본점,4.33,대구 동구 팔공산로185길 55 1층,대구 동구 팔공산로185길 55,35.990312,128.694401

In [89]:
restaurant.to_csv('restaurant_location.csv',index=None)