In [139]:
import pandas as pd
import folium

# CSV 파일 읽어오기
df = pd.read_csv(r'data\아파트_매매_실거래_평균가격_20230810154226.csv', encoding='utf-8')# 지역별 아파트 매매
df

,행정구역별(1),행정구역별(2),2006.01,2006.02,2006.03,2006.04,2006.05,2006.06,2006.07,2006.08,...,2022.08,2022.09,2022.1,2022.11,2022.12,2023.01,2023.02,2023.03,2023.04,2023.05
0,전국,소계,294.6,248.2,269.4,251.9,240.3,215.2,212.7,226.6,...,386.1,377.7,378.6,412.6,435.2,488.9,522.4,510.6,538.6,556.5
1,수도권,소계,383.7,333.6,355.5,324.1,305.5,279.2,273.1,282.5,...,656.3,640.6,621.3,660.6,673.8,722.3,756.9,740.9,781.6,804.4
2,지방,소계,131.8,127.9,127.1,125.8,123.6,121.5,122.9,126,...,290.1,286.7,295.8,304.3,312.4,336.2,351.4,342.8,349.7,351.6
3,서울,서울,521.3,471.6,501.2,451.1,418.3,382,372.3,389.6,...,1242.3,1247.3,1191.7,1275.0,1270.9,1297.5,1358.2,1350.0,1373.5,1434.1
4,서울,도심권,562.6,540.7,551.6,534.3,516.5,479.2,473.3,479,...,1548.4,1216.6,1173.4,1510.4,1409.4,1405.3,1516.3,1549.2,1544.0,1606.5
5,서울,동북권,295,300.4,310.1,307.9,311.2,301.9,301.7,302.6,...,1059.3,1035.8,1017.2,931.0,1033.5,1025.2,1050.0,1056.0,1081.7,1101.8
6,서울,동남권,763.9,760,813.4,758.6,697.1,652.5,658.5,693.5,...,1774.2,2032.0,1767.8,1908.8,1823.4,1834.3,1915.9,1948.1,1963.5,2061.0
7,서울,서북권,376.2,350.8,368.7,364.6,364.4,345.9,340.5,365.3,...,1132.0,1237.3,1078.2,1120.6,1167.9,1216.8,1219.1,1191.7,1247.1,1315.0
8,서울,서남권,416.4,398.4,406.8,380.1,363.9,345.6,346.5,356.6,...,1070.9,1053.1,1031.9,1028.5,1049.9,1118.9,1135.3,1154.3,1167.7,1210.2
9,광역시,부산,151.2,153.1,150.1,146.1,144.9,142.8,146.8,147.7,...,413.3,419.6,446.2,456.7,456.3,501.3,515.7,501.7,517.3,512.6
10,광역시,대구,174,169.7,166.8,166.2,164.2,162.7,162.8,165.3,...,396.8,387.7,399.4,404.8,402.8,410.5,418.8,413.5,421.8,435.2
11,광역시,인천,177,174.1,176.3,179.9,180,183.4,185.9,188,...,496.7,485.2,483.6,500.1,487.9,504.0,518.1,496.4,504.1,506.6
12,광역시,광주,115.5,112.9,113.3,115,110.8,111.3,112,112.1,...,352.6,343.5,342.5,344.4,360.1,368.8,382.4,381.6,381.4,386.0
13,광역시,대전,188,178.3,173.8,180.6,176.1,164.8,160,159.4,...,385.1,401.6,391.6,402.1,398.3,422.8,434.5,414.4,422.4,420.9
14,광역시,울산,127.2,124.7,124.9,130.7,133.6,132.4,130.5,139.5,...,332.8,330.6,331.6,366.0,372.0,386.4,397.9,399.6,390.9,407.9
15,세종,소계,-,-,-,-,-,-,-,-,...,627.9,595.9,623.7,609.2,607.0,595.5,653.6,641.7,652.8,618.0
16,도,경기,308.7,273.4,286.9,275.2,268.7,248.8,240.1,243.8,...,561.2,554.4,545.7,589.9,588.7,618.6,645.1,624.4,645.1,666.3
17,도,강원,100.6,101.8,100.1,100.8,99.8,96.9,99,100.3,...,257.3,242.3,246.6,237.7,245.4,256.5,266.4,262.5,267.1,265.2
18,도,충북,118.4,120.2,119.1,113.5,111.8,124.3,129.7,127.2,...,227.5,233.1,236.6,229.6,254.4,266.1,285.2,277.1,274.7,286.2
19,도,충남,131.9,129,124.4,126.3,121.7,123.6,127.3,129.7,...,243.8,234.6,244.3,245.8,259.0,280.3,286.4,270.8,278.0,280.6
20,도,전북,90.1,89.6,86.8,89.1,88,89,91,94.2,...,225.0,212.1,234.6,235.9,233.0,249.3,258.8,254.2,256.1,272.2
21,도,전남,73.9,72.5,71.6,73.1,74,76,77.4,78.2,...,221.1,213.1,202.7,212.8,211.6,237.0,236.0,228.6,225.1,228.1
22,도,경북,95.1,97.3,97.3,96.9,97.2,99.3,98.1,103.1,...,212.4,218.6,210.0,216.5,219.3,230.8,241.6,234.4,241.9,240.6
23,도,경남,142.7,130.1,132.9,124.8,123.7,123.7,123.9,126.2,...,278.8,276.0,284.0,276.5,285.4,323.2,321.3,310.3,316.8,317.2
24,도,제주,114.9,107.8,112.4,109.9,109.5,126.3,116,127.1,...,429.0,445.7,394.3,403.3,386.4,429.2,440.6,439.0,463.7,471.9

In [140]:
df.drop(df.index[0:3],inplace=True)
df.drop(df.index[1:6],inplace=True)
df.drop('행정구역별(1)',axis=1)

,행정구역별(2),2006.01,2006.02,2006.03,2006.04,2006.05,2006.06,2006.07,2006.08,2006.09,...,2022.08,2022.09,2022.1,2022.11,2022.12,2023.01,2023.02,2023.03,2023.04,2023.05
3,서울,521.3,471.6,501.2,451.1,418.3,382,372.3,389.6,431.9,...,1242.3,1247.3,1191.7,1275.0,1270.9,1297.5,1358.2,1350.0,1373.5,1434.1
9,부산,151.2,153.1,150.1,146.1,144.9,142.8,146.8,147.7,147.1,...,413.3,419.6,446.2,456.7,456.3,501.3,515.7,501.7,517.3,512.6
10,대구,174,169.7,166.8,166.2,164.2,162.7,162.8,165.3,165,...,396.8,387.7,399.4,404.8,402.8,410.5,418.8,413.5,421.8,435.2
11,인천,177,174.1,176.3,179.9,180,183.4,185.9,188,187.2,...,496.7,485.2,483.6,500.1,487.9,504.0,518.1,496.4,504.1,506.6
12,광주,115.5,112.9,113.3,115,110.8,111.3,112,112.1,114.7,...,352.6,343.5,342.5,344.4,360.1,368.8,382.4,381.6,381.4,386.0
13,대전,188,178.3,173.8,180.6,176.1,164.8,160,159.4,168.5,...,385.1,401.6,391.6,402.1,398.3,422.8,434.5,414.4,422.4,420.9
14,울산,127.2,124.7,124.9,130.7,133.6,132.4,130.5,139.5,146.8,...,332.8,330.6,331.6,366.0,372.0,386.4,397.9,399.6,390.9,407.9
15,소계,-,-,-,-,-,-,-,-,-,...,627.9,595.9,623.7,609.2,607.0,595.5,653.6,641.7,652.8,618.0
16,경기,308.7,273.4,286.9,275.2,268.7,248.8,240.1,243.8,265.8,...,561.2,554.4,545.7,589.9,588.7,618.6,645.1,624.4,645.1,666.3
17,강원,100.6,101.8,100.1,100.8,99.8,96.9,99,100.3,98.4,...,257.3,242.3,246.6,237.7,245.4,256.5,266.4,262.5,267.1,265.2
18,충북,118.4,120.2,119.1,113.5,111.8,124.3,129.7,127.2,123.7,...,227.5,233.1,236.6,229.6,254.4,266.1,285.2,277.1,274.7,286.2
19,충남,131.9,129,124.4,126.3,121.7,123.6,127.3,129.7,130.2,...,243.8,234.6,244.3,245.8,259.0,280.3,286.4,270.8,278.0,280.6
20,전북,90.1,89.6,86.8,89.1,88,89,91,94.2,93.6,...,225.0,212.1,234.6,235.9,233.0,249.3,258.8,254.2,256.1,272.2
21,전남,73.9,72.5,71.6,73.1,74,76,77.4,78.2,77,...,221.1,213.1,202.7,212.8,211.6,237.0,236.0,228.6,225.1,228.1
22,경북,95.1,97.3,97.3,96.9,97.2,99.3,98.1,103.1,101.9,...,212.4,218.6,210.0,216.5,219.3,230.8,241.6,234.4,241.9,240.6
23,경남,142.7,130.1,132.9,124.8,123.7,123.7,123.9,126.2,135.2,...,278.8,276.0,284.0,276.5,285.4,323.2,321.3,310.3,316.8,317.2
24,제주,114.9,107.8,112.4,109.9,109.5,126.3,116,127.1,120.9,...,429.0,445.7,394.3,403.3,386.4,429.2,440.6,439.0,463.7,471.9

In [141]:
df01=df[['행정구역별(2)','2017.05','2023.05']]
df01['10년 평균매매가격 변화률']=round((df01['2023.05']-df01['2017.05'])/(df01['2017.05'])*100,1)
df01=df01[['행정구역별(2)','10년 평균매매가격 변화률']]
df01

C:\Users\KDP19\AppData\Local\Temp\ipykernel_8956\1807221525.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df01['10년 평균매매가격 변화률']=round((df01['2023.05']-df01['2017.05'])/(df01['2017.05'])*100,1)

   행정구역별(2)  10년 평균매매가격 변화률
3        서울            82.2
9        부산            43.5
10       대구            30.0
11       인천            53.7
12       광주            49.1
13       대전            56.2
14       울산            33.6
15       소계            68.6
16       경기            55.0
17       강원            31.0
18       충북            38.5
19       충남            36.5
20       전북            42.7
21       전남            23.3
22       경북            30.6
23       경남            29.0
24       제주            16.5

In [142]:
addr_aliases =	{'서울':'서울특별시',	'부산':'부산광역시',	'대구':'대구광역시',	'인천':'인천광역시',	
'광주':'광주광역시',	'대전':'대전광역시',	'울산':'울산광역시',	'경기':'경기도','소계':'세종특별자치시',
'강원':'강원도',	'충북':'충청북도','제주':'제주특별자치도','충남':'충청남도','전북':'전라북도','전남':'전라남도','경북':'경상북도','경남':'경상남도'}
df01['행정구역별(2)']=	df01['행정구역별(2)'].apply(lambda	v:	addr_aliases.get(v,	v))
df01

   행정구역별(2)  10년 평균매매가격 변화률
3     서울특별시            82.2
9     부산광역시            43.5
10    대구광역시            30.0
11    인천광역시            53.7
12    광주광역시            49.1
13    대전광역시            56.2
14    울산광역시            33.6
15  세종특별자치시            68.6
16      경기도            55.0
17      강원도            31.0
18     충청북도            38.5
19     충청남도            36.5
20     전라북도            42.7
21     전라남도            23.3
22     경상북도            30.6
23     경상남도            29.0
24  제주특별자치도            16.5

In [143]:

paldo_map=folium.Map(location=[36,128],zoom_start=8)
geo_path='SIDO_MAP_2022.json' # 시도 경계 데이터

counts = df01['10년 평균매매가격 변화률'].tolist

# 지도에 Choropleth Layer 추가하기
folium.Choropleth(
    geo_data=geo_path,
    data=df01,
    columns=['행정구역별(2)', '10년 평균매매가격 변화률'],
    fill_color='YlOrRd',
    key_on='feature.properties.CTP_KOR_NM',
    vmin=0,  # 값의 최솟값
    vmax=100,  # 값의 최댓값
    fill_opacity=0.8,
    line_opacity=0.5,
).add_to(paldo_map)


# LayerControl 추가하기
folium.LayerControl().add_to(paldo_map)

# 지도를 HTML 파일로 저장하기
paldo_map.save('apart.html')